## YAML Template.
---
is-secured: false
host: <hostname of oci-arcade events>
port: <port of oci-arcade events eg http = 8080, https = 8081>
event-type: <event to use - either serverless or publishevent>